# Generated by Django 5.2.6 on 2025-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link_to_the_payment",
            field=models.CharField(
                blank=True, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
