# Generated by Django 5.2.6 on 2025-10-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payments_link_to_the_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
    ]
