# Generated by Django 5.2.6 on 2025-10-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payments_stripe_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
