# Generated by Django 5.2.6 on 2025-10-31 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_course_stripe_course_id"),
        ("users", "0007_payments_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="lesson_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="materials.lesson",
            ),
        ),
    ]
