# Generated by Django 5.2.6 on 2025-10-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Стоимость курса"),
        ),
    ]
