# Generated by Django 5.2.6 on 2025-10-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_course_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="id_stripe"),
        ),
    ]
