# Generated by Django 5.2.6 on 2025-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_stripe_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="stripe_course_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="id_stripe"
            ),
        ),
    ]
